<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>xyz.zhouxy.plusone</groupId>
    <artifactId>plusone-validator-parent</artifactId>
    <version>1.0.0-SNAPSHOT</version>
  </parent>

  <artifactId>plusone-validator</artifactId>
  <name>plusone-validator</name>

  <description>
    Plusone Validator 是一个校验库，使用 lambda 表达式（包括方法引用）和流式 API 构建校验规则，对对象进行校验。
  </description>

  <licenses>
    <license>
      <name>Apache License, Version 2.0</name>
      <url>https://www.apache.org/licenses/LICENSE-2.0</url>
      <distribution>repo</distribution>
    </license>
  </licenses>

  <developers>
    <developer>
      <name>Zhou Xingyi (周兴毅)</name>
      <url>https://gitea.zhouxy.xyz/plusone</url>
    </developer>
  </developers>

  <scm>
    <connection>scm:git:https://gitea.zhouxy.xyz/plusone/plusone-validator.git</connection>
    <developerConnection>scm:git:ssh://gitea.zhouxy.xyz/plusone/plusone-validator.git</developerConnection>
    <url>https://gitea.zhouxy.xyz/plusone/plusone-validator</url>
  </scm>

  <dependencies>
    <dependency>
      <groupId>xyz.zhouxy.plusone</groupId>
      <artifactId>plusone-commons</artifactId>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>
</project>
