<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>xyz.zhouxy.plusone</groupId>
    <artifactId>plusone-validator-parent</artifactId>
    <version>1.0.0-RC2</version>
  </parent>

  <artifactId>plusone-validator</artifactId>
  <name>plusone-validator</name>

  <description>
    Plusone Validator 是一个校验库，使用 lambda 表达式（包括方法引用）和流式 API 构建校验规则，对对象进行校验。
  </description>

  <dependencies>
    <dependency>
      <groupId>xyz.zhouxy.plusone</groupId>
      <artifactId>plusone-commons</artifactId>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>
</project>
